### ISSUE TITLE
Fingerprint is not stable with stabilitylevel.stable flag it changes many times with device restart and as time changes

### ISSUE THREAD

**Issue by yashctn88** [fingerprintjs/fingerprintjs-android#115]
Fingerprint is not stable with stabilitylevel.stable flag it changes many times with device restart and as time changes also below i have attached the screen shot and the code that i used to generate the fingerprint.

FingerprinterFactory.create(context = context).let {
            it.getFingerprint(version = Fingerprinter.Version.V_5, stabilityLevel = StabilityLevel.STABLE) { fingerprint ->
                Timber.i("Fingerprint: $fingerprint")
            }
}

Same thing i checked in the sample app same issue is being reproduced as well.
![Screenshot_20240625-195223](https://github.com/fingerprintjs/fingerprintjs-android/assets/151529947/bb8876c8-bebd-4c7b-85a8-54993b15bfbd)
![Screenshot_20240626-150217](https://github.com/fingerprintjs/fingerprintjs-android/assets/151529947/0a7e3989-806f-44ab-9be2-faab28aaf2fd)

**Comment by Alexey-Verkhovsky** [comment]
Hello @yashctn88! Thanks for the report. Can you please open navigation drawer, then click the button "Report an issue" and send the raw data to the attached mail (or you may attach it here). Ideally we need the raw data before and after restart (to see what caused the change). Thanks!

**Comment by yashctn88** [comment]
Here are links to the attachment json files for reference

https://drive.google.com/file/d/1P2Kvs6-AFOwPVrQwsBIlGXpYB3kqptc9/view?usp=sharing

https://drive.google.com/file/d/1RVLfwpkXB1A5JtVl5SmYAff2s6jJWxB0/view?usp=sharing

**Comment by Alexey-Verkhovsky** [comment]
@yashctn88 thanks for the files. Now I see that battery capacity has changed for some reason. According to the data we had this was a relatively stable signal, but now looks like it's not that stable. I'll post updates here after conducting a research on this problem.

**Comment by Alexey-Verkhovsky** [comment]
So indeed the values are fluctuating for a small amount of devices. For preserving stability of the stable fingerprint we'll be rounding battery capacity. The fix will be implemented and delivered during Q3 2024.

**Comment by Sergey-Makarov** [comment]
Reopening the issue since it has not been resolved yet.

**Comment by Alexey-Verkhovsky** [comment]
We have addressed this issue in our [latest release](https://github.com/fingerprintjs/fingerprintjs-android/releases/tag/2.2.0).
Starting from `Version = V6`, `BatteryFullCapacitySignal` will not be a part of the `Stable` fingerprint anymore. 

Keep in mind, that:
1. `Stable` fingerprint will lose some of it’s uniqueness that was provided by this signal. But we decided to take this tradeoff to prioritise stability.
2. You will obviously have to implement a migration from the previous versions of fingerprints, because they will change for all users once you update from fingerprint (V1-5, Stable) to (V6, Stable).

These complications are unavoidable because of the fully-local nature of this SDK. It is limited from the POV of identifying retrospectively with fuzzing ML-based logic, so there always will be False Positive and False Negative identifications with provided fingerprints. 

You may tweak the logic by using [custom fingerprints API](https://github.com/fingerprintjs/fingerprintjs-android/blob/main/docs/api_reference.md#raw-signals-access-and-custom-fingerprinting). 

For having better experience consider using [PRO](https://dev.fingerprint.com/docs/native-android-integration).
