### ISSUE TITLE
Code example version seems arbitrary to me

### ISSUE THREAD

**Issue by Valve** [fingerprintjs/fingerprintjs-android#40]
When I'm reading the code example in the readme:

```kotlin
// Initialization
 val fingerprinter = FingerprinterFactory
		.getInstance(applicationContext, Configuration(version = 3))
```

This part `version = 3` seems random and arbitrary to me. 
Why is it 3?
What if we create a constant  `Version.Latest`, which will be `3` now, but will change with every major release?
@Alexey-Verkhovsky

**Comment by Alexey-Verkhovsky** [comment]
I think we steel should keep the version set explicitly. In the current scheme there is no chance that the version will change unexpectedly. But if we change the number to some constant, new users, who integrated the library with using copy/paste approach, after updating the library (Android studio notifies you when newer version is available) will see that fingerprints has changed. And that may be crucial for security applications. 

But I agree that this is arbitrary, I definitely should add mentioning what version is the latest. Also we can create the constant `Version.Latest` but not to place it to the code example to make its usage intentional and mindful.

**Comment by Valve** [comment]
I think we're looking at this differently. The fingerprint version *should* change with every major library version upgrade (according to SemVer).
